  

padelTournamentSystem.class: padelTournamentSystem.java 
	javac -cp .:./src/ojdbc10.jar padelTournamentSystem.java 
	

exe:
	java -cp .:./src/ojdbc10.jar padelTournamentSystem 

clean:
	rm -f *.class
