  

padelTournamentSystem.class: padelTournamentSystem.java jugadoresEntrenadores.java usuariosEntradas.java patrocinadoresColaboradores.java pedidosMateriales.java personalHorarios.java
	javac -cp .:./src/ojdbc10.jar padelTournamentSystem.java 
	

exe:
	java -cp .:./src/ojdbc10.jar padelTournamentSystem 

clean:
	rm -f *.class
